### PR TITLE
fix: copy media link

### LINKED ISSUE #1746: bug: Medias: Copy image link contains
When clicking the "copy link button" in the media library I get urls with extra `:`'s in them

Like this:

```
https:://my-homarr.tld:/api/user-medias/geysohwy2gwjkwkdjwhwhw`
```

Removing the two `:`'s make the link work.

Error seen on ` ghcr.io/homarr-labs/homarr:v1.0.0-beta.6`

### PR DESCRIPTION
**Pull request by manuel-rw**
<br/>
<div align="center">
  
  <h3>Homarr</h3>
</div>

**Thank you for your contribution. Please ensure that your pull request meets the following pull request:**

- [x] Builds without warnings or errors (``pnpm buid``, autofix with ``pnpm format:fix``)
- [x] Pull request targets ``dev`` branch
- [x] Commits follow the [conventional commits guideline](https://www.conventionalcommits.org/en/v1.0.0/)
- [x] No shorthand variable names are used (eg. ``x``, ``y``, ``i`` or any abbrevation)

Closes #1746

### CODE REVIEW

File: apps/nextjs/src/app/[locale]/manage/medias/_actions/copy-media.tsx [hunk 1]
```diff
@@ -15,7 +15,7 @@ export const CopyMedia = ({ media }: CopyMediaProps) => {
 
   const url =
     typeof window !== "undefined"
-      ? `${window.location.protocol}://${window.location.hostname}:${window.location.port}/api/user-medias/${media.id}`
+      ? `${window.location.protocol}//${window.location.hostname}:${window.location.port}/api/user-medias/${media.id}`
```
Comment (Meierschlumpf) [inline apps/nextjs/src/app/[locale]/manage/medias/_actions/copy-media.tsx:18]: I think we can fix another issue here when we remove the port thing when it's not set (empty string)

**Review by Meierschlumpf — CHANGES_REQUESTED** [review]

**Review by Meierschlumpf — DISMISSED** [review]

**Comment by Meierschlumpf** [comment]
I'll fix the deepsource issue real quick

**Comment by Meierschlumpf** [comment]
Okay I used `origin` instead of `protocol`, `hostname` and `port` combined as it combines all of them without us having to deal with it :joy:

**Review by Meierschlumpf — APPROVED** [review]
