### PR TITLE
fix(boards): selection menu not shown to users without change access

### LINKED ISSUE #4688: bug(boards): selection menu not shown to users without change access
### Describe the bug

As a user on our [Discord](https://discord.com/channels/972958686051962910/1450661600716394548) noticed, the `<SelectBoardsMenu />` is not visible to users without change access.

### Steps to reproduce

1. Login as user without access to change a certain board (but allow to view it)
2. Navigate to that board
3. The board selection menu is not shown

### Impact

Minor, certain users can not use the quick way to switch between boards in the header.

### Additional information

_No response_

### Version

1.46.0

### Installation method

Docker Run

### Browser

Chrome

### PR DESCRIPTION
**Pull request by Meierschlumpf**
<br/>
<div align="center">
  
  <h3>Homarr</h3>
</div>

**Thank you for your contribution. Please ensure that your pull request meets the following pull request:**

- [x] Builds without warnings or errors (`pnpm build`, autofix with `pnpm format:fix`)
- [x] Pull request targets `dev` branch
- [x] Commits follow the [conventional commits guideline](https://www.conventionalcommits.org/en/v1.0.0/)
- [x] No shorthand variable names are used (eg. `x`, `y`, `i` or any abbrevation)
- [x] Documentation is up to date. Create a pull request [here](https://github.com/homarr-labs/documentation/).

Closes #4688

### CODE REVIEW

File: apps/nextjs/src/app/[locale]/boards/(content)/_header-actions.tsx [hunk 1]
```diff
@@ -44,7 +44,7 @@ export const BoardContentHeaderActions = () => {
   const { hasChangeAccess } = useBoardPermissions(board);
 
   if (!hasChangeAccess) {
-    return null; // Hide actions for user without access
+    return <SelectBoardsMenu />; // Hide actions for user without access
```
Comment (Meierschlumpf) [inline apps/nextjs/src/app/[locale]/boards/(content)/_header-actions.tsx]:
```suggestion
    return <SelectBoardsMenu />; // Hide change actions for users without access
```

File: apps/nextjs/src/app/[locale]/boards/(content)/_header-actions.tsx [hunk 2]
```diff
@@ -44,7 +44,7 @@ export const BoardContentHeaderActions = () => {
   const { hasChangeAccess } = useBoardPermissions(board);
 
   if (!hasChangeAccess) {
-    return null; // Hide actions for user without access
+    return <SelectBoardsMenu />; // Hide change actions for users without access
```
Comment (manuel-rw) [inline apps/nextjs/src/app/[locale]/boards/(content)/_header-actions.tsx]: You're not hiding anything...
