### PR TITLE
fix(auth): fusion auth returns www-authenticate token response

### LINKED ISSUE #2690: bug: OIDC configuration throws: server responded with a challenge in the WWW-Authenticate HTTP Header
### Describe the bug

I have configured OIDC auth provider for Homarr, but when logging in via my IdP (locally hosted FusionAuth), i get redirected to https://homarr.my.domain/auth/login?error=Configuration. The logs show the following:

See the logs below for homarr error message.

I have configured homarr like so:

    environment:
      SECRET_ENCRYPTION_KEY: <secret_key>
      AUTH_PROVIDERS: oidc,credentials
      AUTH_LOGOUT_REDIRECT_URL: https://homarr.my.domain
      AUTH_OIDC_ISSUER: https://auth.my.domain
      AUTH_OIDC_CLIENT_ID: <client_id from fusionauth>
      AUTH_OIDC_CLIENT_SECRET: <client_secret from fusionauth>
      AUTH_OIDC_CLIENT_NAME: FusionAuth
      AUTH_OIDC_SCOPE_OVERWRITE: openid email profile
      AUTH_OIDC_GROUPS_ATTRIBUTE: roles
I've configured fusionauth the same way as the example for Azure on the homarr docs (https://homarr.dev/docs/advanced/single-sign-on/ in the "example setup" section) since FusionAuth does not support setting custom claims with the licence I'm using.

I've tried searching the internet and also going to the link thats provided in the log (https://authjs.dev/reference/core/errors#callbackrouteerror) but I'm not seeing what the issue is.

### Logs
```
2025-03-24T15:15:29.361Z info: Dispatching request https://auth.my.domain/.well-known/openid-configuration (5 headers)
2025-03-24T15:15:29.810Z info: Dispatching request https://auth.my.domain/.well-known/openid-configuration (5 headers)
2025-03-24T15:15:29.935Z info: Dispatching request https://auth.my.domain/oauth2/token (8 headers)
2025-03-24T15:15:30.036Z error: C: Read more at [https://errors.authjs.dev#callbackrouteerror](https://errors.authjs.dev/#callbackrouteerror)
  at oZ (/app/apps/nextjs/.next/server/chunks/8287.js:489:48234)
  at async o8 (/app/apps/nextjs/.next/server/chunks/8287.js:489:54738)
  at async ae (/app/apps/nextjs/.next/server/chunks/8287.js:489:57629)
  at async c (/app/apps/nextjs/.next/server/app/api/auth/[...nextauth]/route.js:1:3578)
  at async tr.do (/app/node_modules/next/dist/compiled/next-server/app-route.runtime.prod.js:18:17582)
  at async tr.handle (/app/node_modules/next/dist/compiled/next-server/app-route.runtime.prod.js:18:22212)
  at async doRender (/app/node_modules/next/dist/server/base-server.js:1452:42)
  at async responseGenerator (/app/node_modules/next/dist/server/base-server.js:1822:28)
  at async NextNodeServer.renderToResponseWithComponentsImpl (/app/node_modules/next/dist/server/base-server.js:1832:28)
The above error also had these properties on it:
{
  cause: {
    '0': { scheme: 'basic', parameters: {} },
    err: sl: server responded with a challenge in the WWW-Authenticate HTTP Header
        at sR (.next/server/chunks/8287.js:489:19557)
        at sP (.next/server/chunks/8287.js:489:23701)
        at sV (.next/server/chunks/8287.js:489:23361)
        at oL (.next/server/chunks/8287.js:489:37318)
        at async oZ (.next/server/chunks/8287.js:489:43495)
        at async o8 (.next/server/chunks/8287.js:489:54738)
        at async ae (.next/server/chunks/8287.js:489:57629)
        at async c (.next/server/app/api/auth/[...nextauth]/route.js:1:3578) {
      code: 'OAUTH_WWW_AUTHENTICATE_CHALLENGE',
      status: 200,
      [cause]: [ { scheme: 'basic', parameters: {} } ]
    },
    provider: 'oidc'
  },
  name: 'C',
  type: 'CallbackRouteError',
  kind: 'error'
}
2025-03-24T15:15:30.038Z error: [object Object]
The above error also had these properties on it:
{
  '0': { scheme: 'basic', parameters: {} },
  err: sl: server responded with a challenge in the WWW-Authenticate HTTP Header
      at sR (.next/server/chunks/8287.js:489:19557)
      at sP (.next/server/chunks/8287.js:489:23701)
      at sV (.next/server/chunks/8287.js:489:23361)
      at oL (.next/server/chunks/8287.js:489:37318)
      at async oZ (.next/server/chunks/8287.js:489:43495)
      at async o8 (.next/server/chunks/8287.js:489:54738)
      at async ae (.next/server/chunks/8287.js:489:57629)
      at async c (.next/server/app/api/auth/[...nextauth]/route.js:1:3578) {
    code: 'OAUTH_WWW_AUTHENTICATE_CHALLENGE',
    status: 200,
    [cause]: [ { scheme: 'basic', parameters: {} } ]
  },
  provider: 'oidc'
}
```

### Steps to reproduce

See configuration description above.

### Impact

Can't use OIDC login.

### Additional information

_No response_

### Version

1.11.0

### Installation method

Portainer

### Browser

Chrome

### PR DESCRIPTION
**Pull request by Meierschlumpf**
<br/>
<div align="center">
  
  <h3>Homarr</h3>
</div>

**Thank you for your contribution. Please ensure that your pull request meets the following pull request:**

- [x] Builds without warnings or errors (``pnpm build``, autofix with ``pnpm format:fix``)
- [x] Pull request targets ``dev`` branch
- [x] Commits follow the [conventional commits guideline](https://www.conventionalcommits.org/en/v1.0.0/)
- [x] No shorthand variable names are used (eg. ``x``, ``y``, ``i`` or any abbrevation)

Closes #2690

### CODE REVIEW

File: packages/auth/providers/oidc/oidc-provider.ts [hunk 1]
```diff
@@ -22,6 +22,24 @@ export const OidcProvider = (headers: ReadonlyHeaders | null): OIDCConfig<Profil
       redirect_uri: createRedirectUri(headers, "/api/auth/callback/oidc", "https"),
     },
   },
+  token: {
+    // Providers like fusionauth may return ww-authenticate which results in an error
```
Comment (Meierschlumpf) [inline packages/auth/providers/oidc/oidc-provider.ts:26]:
```suggestion
    // Providers like fusionauth may return www-authenticate which results in an error
```

**Review by manuel-rw — APPROVED** [review]
