### PR TITLE
fix: characters are not considered Symbols when entering a new password

### LINKED ISSUE #3645: bug: Characters are not considered Symbols when entering a new password
### Describe the bug

Homarr Version 1.28.1

When creating a new user, or changing a password, the following characters will not be considered a symbol for password strength:
Tilde ( ~ )
Backtick ( ` )
DoubleQuote ( " )
Underscore ( _ )
ForwardSlash ( / )
BackSlash ( \ )
Brackets ( [] )
Braces ( {} )
Space (   )

Image

### Steps to reproduce

Standard Docker Installation, create a password with one of the previous characters, another "symbol" will be required.

### Impact

Homarr is still usable
This reduces the possible complexity of user passwords by constraining the possibility pool.

### Additional information

_No response_

### Version

1.28.1

### Installation method

Docker Compose

### Browser

Firefox

### PR DESCRIPTION
**Pull request by NikeLaosClericus**
<br/>
<div align="center">
  
  <h3>Homarr</h3>
</div>

**Thank you for your contribution. Please ensure that your pull request meets the following pull request:**

- [x] Builds without warnings or errors (`pnpm build`, autofix with `pnpm format:fix`)
- [x] Pull request targets `dev` branch
- [x] Commits follow the [conventional commits guideline](https://www.conventionalcommits.org/en/v1.0.0/)
- [x] No shorthand variable names are used (eg. `x`, `y`, `i` or any abbrevation)
- [x] Documentation is up to date. Create a pull request [here](https://github.com/homarr-labs/documentation/).

Closes #3645

### CODE REVIEW

**Comment by NikeLaosClericus** [comment]
Removed unnecessary escape characters.

File: packages/validation/src/user.ts [hunk 1]
```diff
@@ -16,7 +16,7 @@ export const passwordRequirements = [
   { check: regexCheck(/[a-z]/), value: "lowercase" },
   { check: regexCheck(/[A-Z]/), value: "uppercase" },
   { check: regexCheck(/\d/), value: "number" },
-  { check: regexCheck(/[$&+,:;=?@#|'<>.^*()%!-]/), value: "special" },
+  { check: regexCheck(/[$&+,:;=?@#|'<>.^*()%!\-~`"_/\\\[\]{} ]/), value: "special" },
```
Comment (Meierschlumpf) [inline packages/validation/src/user.ts]:
```suggestion
  { check: regexCheck(/[$&+,:;=?@#|'<>.^*()%!\-~`"_/\\\[\]{}]/), value: "special" },
```
I would suggest, that we remove the space as special character

**Comment by Meierschlumpf** [comment]
Also we can fix one more unnecessary escape issue: `Error:   19:55  error  Unnecessary escape character: \[  no-useless-escape`

File: packages/validation/src/user.ts (hunk 1 above)
Comment (NikeLaosClericus) [reply packages/validation/src/user.ts]: I liked the idea of also allowing passphrases using spaces:
password_strength_2x

But individually is it less secure than any other special character?
Any character exclusions we make technically make all passwords less secure because the candidate pool is smaller, but it might not be that big of a deal.

Is there a technical reason why spaces might be bad?

Comment (Meierschlumpf) [reply packages/validation/src/user.ts]: I mean you can still use spaces, you just need to have other special characters in there. I just think it's not really a special character

File: packages/validation/src/user.ts [hunk 2]
```diff
@@ -16,7 +16,7 @@ export const passwordRequirements = [
   { check: regexCheck(/[a-z]/), value: "lowercase" },
   { check: regexCheck(/[A-Z]/), value: "uppercase" },
   { check: regexCheck(/\d/), value: "number" },
-  { check: regexCheck(/[$&+,:;=?@#|'<>.^*()%!-]/), value: "special" },
+  { check: regexCheck(/[$&+,:;=?@#|'<>.^*()%!\-~`"_/\\[\]{} ]/), value: "special" },
```
Comment (Meierschlumpf) [inline packages/validation/src/user.ts]:
```suggestion
  { check: regexCheck(/[$&+,:;=?@#|'<>.^*()%!\-~`"_/\\[\]{}]/), value: "special" },
```

**Review by Meierschlumpf — APPROVED** [review]
